package de.coonabibba.bikeyboard

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * Checks the wordlists that actually ship.
 *
 * They are generated by `scripts/build-wordlists.py`, which folds words in
 * Python and sorts by the result; the app binary-searches that order using
 * [Folding], in Kotlin. Nothing but this test keeps the two implementations
 * from drifting apart, and the failure mode if they do is suggestions quietly
 * going missing for part of the alphabet.
 */
class WordlistAssetTest {

    private fun asset(name: String): File {
        // Unit tests run from the module directory, but do not depend on it.
        val candidates = listOf(
            File("src/main/assets/wordlists/$name"),
            File("app/src/main/assets/wordlists/$name"),
        )
        return candidates.firstOrNull { it.exists() }
            ?: error("wordlist $name not found; looked in ${candidates.map { it.absolutePath }}")
    }

    /** No near misses recorded — a word read back rather than typed (D37). */
    private fun untouched(word: String) = word.map(TypedTouch::untouched)

    private fun entries(name: String): List<Pair<String, Long>> =
        asset(name).readLines()
            .filterNot { it.isEmpty() || it.startsWith("#") }
            .map { line ->
                val parts = line.split('\t')
                assertEquals("malformed line: $line", 2, parts.size)
                parts[0] to parts[1].toLong()
            }

    private fun eachList(check: (String, List<Pair<String, Long>>) -> Unit) {
        listOf("de.txt", "en.txt").forEach { check(it, entries(it)) }
    }

    @Test
    fun `both wordlists are substantial`() {
        eachList { name, entries ->
            assertTrue("$name has only ${entries.size} entries", entries.size > 20_000)
        }
    }

    /** The order the app's binary search depends on. */
    @Test
    fun `entries are sorted by the app's own folding`() {
        eachList { name, entries ->
            var previous = ""
            entries.forEach { (word, _) ->
                val folded = Folding.fold(word)
                assertTrue(
                    "$name is out of folded order: $previous then $folded ($word)",
                    folded >= previous,
                )
                previous = folded
            }
        }
    }

    @Test
    fun `every count is a positive number`() {
        eachList { name, entries ->
            entries.forEach { (word, count) ->
                assertTrue("$name: $word has count $count", count > 0)
            }
        }
    }

    /** One casing per word, or two slots of the strip say the same thing. */
    @Test
    fun `no word appears twice, in any casing`() {
        eachList { name, entries ->
            val seen = HashSet<String>(entries.size * 2)
            entries.forEach { (word, _) ->
                assertTrue("$name lists ${word.lowercase()} more than once", seen.add(word.lowercase()))
            }
        }
    }

    @Test
    fun `words carry no whitespace or digits`() {
        eachList { name, entries ->
            entries.forEach { (word, _) ->
                assertTrue(
                    "$name: unexpected characters in $word",
                    word.all { it.isLetter() || it == '\'' || it == '-' },
                )
            }
        }
    }

    /** Provenance travels with the file, per D13. */
    @Test
    fun `each file names its sources in a header`() {
        eachList { name, _ ->
            val header = asset(name).readLines().takeWhile { it.startsWith("#") }.joinToString("\n")
            assertTrue("$name has no header", header.isNotEmpty())
            listOf("Vocabulary and casing", "Frequencies", "build-wordlists.py").forEach {
                assertTrue("$name header does not mention $it", it in header)
            }
        }
    }

    @Test
    fun `the German list has German words, correctly capitalised`() {
        val words = entries("de.txt").map { it.first }.toSet()
        listOf("Haus", "Häuser", "Straße", "über", "nicht", "gehen").forEach {
            assertTrue("de.txt is missing $it", it in words)
        }
    }

    @Test
    fun `the English list has English words`() {
        val words = entries("en.txt").map { it.first }.toSet()
        listOf("the", "keyboard", "I", "have").forEach {
            assertTrue("en.txt is missing $it", it in words)
        }
    }

    // -- end to end, on the real lists ---------------------------------------

    private fun realSource(): DictionarySuggestions {
        val open = { name: String -> asset(name.removePrefix("wordlists/")).inputStream() }
        return DictionarySuggestions(
            lexicons = listOf(
                Wordlists.load(open, Wordlists.GERMAN, Language.GERMAN),
                Wordlists.load(open, Wordlists.ENGLISH, Language.ENGLISH),
            ),
            personal = PersonalStore(File(folder(), "personal-words.txt")),
        )
    }

    private fun folder(): File = File(System.getProperty("java.io.tmpdir"), "bikeyboard-test")
        .apply { mkdirs() }

    @Test
    fun `real lists suggest real words`() {
        val source = realSource()
        assertTrue("Haus" in source.suggest("hau", untouched("hau")).map { it.text })
        assertTrue("keyboard" in source.suggest("keyboa", untouched("keyboa")).map { it.text })
    }

    /** D5's cheap win: the umlaut is a long-press, so typing without it must work. */
    @Test
    fun `a skipped umlaut finds the word on the real lists`() {
        assertTrue("über" in realSource().suggest("ube", untouched("ube")).map { it.text })
    }

    /**
     * D1 and D2, on the real data: no current language, and a prefix common to
     * both languages produces candidates from both.
     */
    @Test
    fun `both languages answer the same prefix`() {
        val source = realSource()
        val german = entries("de.txt").map { it.first }.toSet()
        val english = entries("en.txt").map { it.first }.toSet()
        // "in" starts words in both, and nothing about the keyboard's state
        // says which language is being typed.
        val suggestions = source.suggest("inte", untouched("inte")).map { it.text }
        assertTrue("nothing suggested", suggestions.isNotEmpty())
        assertTrue(
            "no English candidate in $suggestions",
            suggestions.any { it in english && it !in german },
        )
    }
}
